apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heatwise-view.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "heatwise-view.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "heatwise-view.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "heatwise-view.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # Prometheus scraping on actuator port (if you don't use ServiceMonitor)
        {{- if not .Values.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.actuatorPort }}"
        prometheus.io/path: "/actuator/prometheus"
        {{- end }}
        {{- with .Values.podAnnotations }}{{ toYaml . | nindent 8 }}{{- end }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: actuator
              containerPort: {{ .Values.service.actuatorPort }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: state-store
              mountPath: /var/lib/kafka-streams
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: actuator
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: actuator
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: state-store
          persistentVolumeClaim:
            claimName: {{ include "heatwise-view.name" . }}-pvc
      {{- end }}
