apiVersion: v1
kind: Service
metadata:
  name: {{ include "heatwise-view.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "heatwise-view.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "heatwise-view.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: actuator
      port: {{ .Values.service.actuatorPort }}
      targetPort: actuator
