apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heatwise-ui.fullname" . }}
  labels:
    {{- include "heatwise-ui.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toJson .Values.uiConfig | nindent 4 }}