apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heatwise-ui.fullname" . }}
  labels:
    {{- include "heatwise-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "heatwise-ui.fullname" . }}
      app.kubernetes.io/name: {{ include "heatwise-ui.name" . }}
  template:
    metadata:
      labels:
        {{- include "heatwise-ui.labels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ui-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: ui-config
          configMap:
            name: {{ include "heatwise-ui.fullname" . }}
            items:
              - key: config.json
                path: config.json