apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.kafka.image.tag | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.kafka.service.type }}
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: tcp-kafka
      port: {{ .Values.kafka.service.port }}
      targetPort: 9092
      {{- if and (eq .Values.kafka.service.type "NodePort") (ne .Values.kafka.nodePort 0) }}
      nodePort: {{ .Values.kafka.nodePort }}
      {{- end }}
