[versions]

[libraries]
sttp-circe='com.softwaremill.sttp.client4:circe_3:4.0.13'



junit-platform-launcher="org.junit.platform:junit-platform-launcher:1.13.1"
junit-platform-engine="org.junit.platform:junit-platform-engine:1.13.1"
junit-scala-test-plus="org.scalatestplus:junit-5-13_3:3.2.19.0"

logback='ch.qos.logback:logback-classic:1.5.20'

pekko-http='org.apache.pekko:pekko-http_3:1.3.0'
pekko-http-backend="com.softwaremill.sttp.client4:pekko-http-backend_3:4.0.13"
pekko-testkit="org.apache.pekko:pekko-actor-testkit-typed_3:1.2.1"
pekko-stream='org.apache.pekko:pekko-stream_3:1.2.1'
pekko-actor='org.apache.pekko:pekko-actor-typed_3:1.2.1'

puml="net.sourceforge.plantuml:plantuml:1.2024.7"

pureconfig-core="com.github.pureconfig:pureconfig-core_3:0.17.9"
pureconfig-generic-scala3="com.github.pureconfig:pureconfig-generic-scala3_3:0.17.9"

sttp-core='com.softwaremill.sttp.client4:core_3:4.0.13'
sttp-pekko-backend='com.softwaremill.sttp.client4:pekko-http-backend_3:4.0.13'

scala="org.scala-lang:scala-library:3.3.4"
scala-test="org.scalatest:scalatest_3:3.2.19"

[bundles]


[plugins]
