apiVersion: v2
name: heatwise-stack
description: Heatwise app + minimal Apache Kafka (KRaft) using docker.io/apache/kafka
type: application
version: 0.4.0

dependencies:
  - name: heatwise
    version: 0.3.0
    repository: "file://./charts/heatwise"
  - name: heatwise-view
    version: 0.1.0
    repository: "file://./charts/heatwise-view"
  - name: heatwise-ui
    version: 0.1.0
    repository: "file://./charts/heatwise-ui"