apiVersion: v2
name: heatwise-stack
description: Heatwise app + minimal Apache Kafka (KRaft) using docker.io/apache/kafka
type: application
version: 0.4.0

dependencies:
  - name: heatwise
    version: 0.2.0
    repository: "file://../heatwise"
