apiVersion: v2
name: heatwise-stack
description: Heatwise app + Kafka (dev stack)
type: application
version: 0.1.0

dependencies:
  - name: kafka
    version: 28.2.0
    repository: https://charts.bitnami.com/bitnami
    alias: kafka
  - name: heatwise
    version: 0.1.0
    repository: "file://../heatwise"
