# Minimal Pi overrides
nodeSelector:
  kubernetes.io/arch: arm64

kafka:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi

  storage:
    enabled: true
    size: 5Gi
    storageClass: local-path

heatwise:
  image:
    tag: "0.7.3"
heatwise-view:
  image:
    tag: "0.7.3"


