apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heatwise.name" . }}
  labels:
    {{- include "heatwise.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "heatwise.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "heatwise.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.javaToolOptions | quote }}
            - name: DECISIONS_DIR
              value: {{ .Values.persistence.mountPath | default "/data" | quote }}
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- if .Values.temperatureSensor.enabled }}
            - name: W1_PATH
              value: {{ .Values.temperatureSensor.path | quote }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /ready, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /live, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
            {{- if .Values.temperatureSensor.enabled }}
            - name: w1
              mountPath: {{ .Values.temperatureSensor.w1.mountPath }}
              readOnly: true
            {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "heatwise.name" . }}-pvc
      {{- if .Values.temperatureSensor.enabled }}
        - name: w1
          hostPath:
            path: {{ .Values.temperatureSensor.w1.hostPath }}
            type: Directory
      {{- end }}
      {{- end }}
